name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies 🔧
        run: npm ci

      - name: Build 🏗️
        run: npm run build:prod

      - name: Copy index.html to 404.html 📄
        run: cp dist/impulso360/browser/index.html dist/impulso360/browser/404.html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/impulso360/browser
          branch: gh-pages # The branch the action will deploy to.
